[theme]
theme = "slick"
[icons]
icons = "awesome5"

[[block]]
block = "net"
device = "enp9s0u2u1u2"
interval = 5

[[block]]
block = "net"
device = "wlp3s0"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20

[[block]]
block = "memory"
format = " $mem_avail "

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = " $percentage% $time "

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = " $percentage% $time "

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d.%m %T', l:de_DE) "
