theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "enp0s31f6"
ip = true
interval = 5

[[block]]
block = "net"
device = "wlp3s0"
ip = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MAg}G"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}°|{max}°|{average}°"

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%a %d.%m %T"
