theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "enp9s0u2u1u2"
interval = 5

[[block]]
block = "net"
device = "wlp3s0"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_avail}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%a %d.%m %T"
