add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
disabled = true
[package]
disabled = true
[docker_context]
disabled = true
[nodejs]
disabled = true
[java]
disabled = true
[battery]
disabled = true
